// Generated from ui/wasm/wisdom-chess.idl. Do not edit.
// Regenerate with: npm run generate:wasm-types
export default WisdomChessModule;
declare function WisdomChessModule<T>(target?: T): Promise<T & typeof WisdomChessModule>;
declare module WisdomChessModule {
    function destroy(obj: any): void;
    function _malloc(size: number): number;
    function _free(ptr: number): void;
    function wrapPointer<C extends new (...args: any) => any>(ptr: number, Class: C): InstanceType<C>;
    function getPointer(obj: unknown): number;
    function castObject<C extends new (...args: any) => any>(object: unknown, Class: C): InstanceType<C>;
    function compare(object1: unknown, object2: unknown): boolean;
    const HEAP8: Int8Array;
    const HEAP16: Int16Array;
    const HEAP32: Int32Array;
    const HEAPU8: Uint8Array;
    const HEAPU16: Uint16Array;
    const HEAPU32: Uint32Array;
    const HEAPF32: Float32Array;
    const HEAPF64: Float64Array;
    const Human: wisdom_WebPlayer;
    const ChessEngine: wisdom_WebPlayer;
    type wisdom_WebPlayer = number & { readonly __enum: 'wisdom_WebPlayer' };
    function _emscripten_enum_wisdom_WebPlayer_Human(): wisdom_WebPlayer;
    function _emscripten_enum_wisdom_WebPlayer_ChessEngine(): wisdom_WebPlayer;
    const NoColor: wisdom_WebColor;
    const White: wisdom_WebColor;
    const Black: wisdom_WebColor;
    type wisdom_WebColor = number & { readonly __enum: 'wisdom_WebColor' };
    function _emscripten_enum_wisdom_WebColor_NoColor(): wisdom_WebColor;
    function _emscripten_enum_wisdom_WebColor_White(): wisdom_WebColor;
    function _emscripten_enum_wisdom_WebColor_Black(): wisdom_WebColor;
    const NoPiece: wisdom_WebPiece;
    const Pawn: wisdom_WebPiece;
    const Knight: wisdom_WebPiece;
    const Bishop: wisdom_WebPiece;
    const Rook: wisdom_WebPiece;
    const Queen: wisdom_WebPiece;
    const King: wisdom_WebPiece;
    type wisdom_WebPiece = number & { readonly __enum: 'wisdom_WebPiece' };
    function _emscripten_enum_wisdom_WebPiece_NoPiece(): wisdom_WebPiece;
    function _emscripten_enum_wisdom_WebPiece_Pawn(): wisdom_WebPiece;
    function _emscripten_enum_wisdom_WebPiece_Knight(): wisdom_WebPiece;
    function _emscripten_enum_wisdom_WebPiece_Bishop(): wisdom_WebPiece;
    function _emscripten_enum_wisdom_WebPiece_Rook(): wisdom_WebPiece;
    function _emscripten_enum_wisdom_WebPiece_Queen(): wisdom_WebPiece;
    function _emscripten_enum_wisdom_WebPiece_King(): wisdom_WebPiece;
    const Playing: wisdom_WebGameStatus;
    const Checkmate: wisdom_WebGameStatus;
    const Stalemate: wisdom_WebGameStatus;
    const ThreefoldRepetitionReached: wisdom_WebGameStatus;
    const ThreefoldRepetitionAccepted: wisdom_WebGameStatus;
    const FivefoldRepetitionDraw: wisdom_WebGameStatus;
    const FiftyMovesWithoutProgressReached: wisdom_WebGameStatus;
    const FiftyMovesWithoutProgressAccepted: wisdom_WebGameStatus;
    const SeventyFiveMovesWithoutProgressDraw: wisdom_WebGameStatus;
    const InsufficientMaterialDraw: wisdom_WebGameStatus;
    type wisdom_WebGameStatus = number & { readonly __enum: 'wisdom_WebGameStatus' };
    function _emscripten_enum_wisdom_WebGameStatus_Playing(): wisdom_WebGameStatus;
    function _emscripten_enum_wisdom_WebGameStatus_Checkmate(): wisdom_WebGameStatus;
    function _emscripten_enum_wisdom_WebGameStatus_Stalemate(): wisdom_WebGameStatus;
    function _emscripten_enum_wisdom_WebGameStatus_ThreefoldRepetitionReached(): wisdom_WebGameStatus;
    function _emscripten_enum_wisdom_WebGameStatus_ThreefoldRepetitionAccepted(): wisdom_WebGameStatus;
    function _emscripten_enum_wisdom_WebGameStatus_FivefoldRepetitionDraw(): wisdom_WebGameStatus;
    function _emscripten_enum_wisdom_WebGameStatus_FiftyMovesWithoutProgressReached(): wisdom_WebGameStatus;
    function _emscripten_enum_wisdom_WebGameStatus_FiftyMovesWithoutProgressAccepted(): wisdom_WebGameStatus;
    function _emscripten_enum_wisdom_WebGameStatus_SeventyFiveMovesWithoutProgressDraw(): wisdom_WebGameStatus;
    function _emscripten_enum_wisdom_WebGameStatus_InsufficientMaterialDraw(): wisdom_WebGameStatus;
    class WebColoredPiece {
        constructor(id: number, color: wisdom_WebColor, piece: wisdom_WebPiece, row: number, col: number);
        get_id(): number;
        set_id(id: number): void;
        id: number;
        get_color(): wisdom_WebColor;
        set_color(color: wisdom_WebColor): void;
        color: wisdom_WebColor;
        get_piece(): wisdom_WebPiece;
        set_piece(piece: wisdom_WebPiece): void;
        piece: wisdom_WebPiece;
        get_row(): number;
        set_row(row: number): void;
        row: number;
        get_col(): number;
        set_col(col: number): void;
        col: number;
    }
    class WebColoredPieceList {
        constructor();
        get_pieces(index: number): WebColoredPiece;
        set_pieces(index: number, pieces: WebColoredPiece): void;
        pieces: WebColoredPiece;
        pieceAt(index: number): WebColoredPiece;
        get_length(): number;
        set_length(length: number): void;
        length: number;
    }
    class GameSettings {
        constructor();
        constructor(whitePlayer: wisdom_WebPlayer, blackPlayer: wisdom_WebPlayer, thinkingTime: number, searchDepth: number);
        get_whitePlayer(): wisdom_WebPlayer;
        set_whitePlayer(whitePlayer: wisdom_WebPlayer): void;
        whitePlayer: wisdom_WebPlayer;
        get_blackPlayer(): wisdom_WebPlayer;
        set_blackPlayer(blackPlayer: wisdom_WebPlayer): void;
        blackPlayer: wisdom_WebPlayer;
        get_thinkingTime(): number;
        set_thinkingTime(thinkingTime: number): void;
        thinkingTime: number;
        get_searchDepth(): number;
        set_searchDepth(searchDepth: number): void;
        searchDepth: number;
        get_debugLogging(): boolean;
        set_debugLogging(debugLogging: boolean): void;
        debugLogging: boolean;
    }
    const NotReached: wisdom_WebDrawStatus;
    const Proposed: wisdom_WebDrawStatus;
    const Accepted: wisdom_WebDrawStatus;
    const Declined: wisdom_WebDrawStatus;
    type wisdom_WebDrawStatus = number & { readonly __enum: 'wisdom_WebDrawStatus' };
    function _emscripten_enum_wisdom_WebDrawStatus_NotReached(): wisdom_WebDrawStatus;
    function _emscripten_enum_wisdom_WebDrawStatus_Proposed(): wisdom_WebDrawStatus;
    function _emscripten_enum_wisdom_WebDrawStatus_Accepted(): wisdom_WebDrawStatus;
    function _emscripten_enum_wisdom_WebDrawStatus_Declined(): wisdom_WebDrawStatus;
    const ThreefoldRepetition: wisdom_WebDrawByRepetitionType;
    const FiftyMovesWithoutProgress: wisdom_WebDrawByRepetitionType;
    type wisdom_WebDrawByRepetitionType = number & { readonly __enum: 'wisdom_WebDrawByRepetitionType' };
    function _emscripten_enum_wisdom_WebDrawByRepetitionType_ThreefoldRepetition(): wisdom_WebDrawByRepetitionType;
    function _emscripten_enum_wisdom_WebDrawByRepetitionType_FiftyMovesWithoutProgress(): wisdom_WebDrawByRepetitionType;
    class WebGame {
        getPieceList(): WebColoredPieceList;
        needsPawnPromotion(src: string, dst: string): boolean;
        makeHumanMove(src: string, dst: string, pieceType: wisdom_WebPiece): number;
        makeComputerMove(moveText: string): void;
        setSettings(newSettings: GameSettings): void;
        getInCheck(): boolean;
        getMoveStatus(): string;
        getGameOverStatus(): string;
        get_moveNumber(): number;
        set_moveNumber(moveNumber: number): void;
        moveNumber: number;
        getGameId(): number;
        getCurrentTurn(): wisdom_WebColor;
        getGameStatus(): wisdom_WebGameStatus;
        getPlayerOfColor(color: wisdom_WebColor): wisdom_WebPlayer;
        setComputerDrawStatus(type: wisdom_WebDrawByRepetitionType, who: wisdom_WebColor, accepted: boolean): void;
        setHumanDrawStatus(type: wisdom_WebDrawByRepetitionType, who: wisdom_WebColor, accepted: boolean): void;
    }
    class GameModel {
        constructor();
        sendPause(): void;
        sendUnpause(): void;
        notifyHumanMove(packedMove: number): void;
        notifyComputerMove(): void;
        startNewGame(): WebGame;
        getCurrentGameSettings(): GameSettings;
        setCurrentGameSettings(newSettings: GameSettings): void;
        getFirstHumanPlayerColor(): wisdom_WebColor;
        getSecondHumanPlayerColor(): wisdom_WebColor;
        getMinThinkingTime(): number;
        getMaxThinkingTime(): number;
        getMinSearchDepth(): number;
        getMaxSearchDepth(): number;
    }
}