enum wisdom_WebPlayer {
  "wisdom::Human",
  "wisdom::ChessEngine"
};

[Prefix="wisdom::"]
interface WebGame {
    void WebGame(long white_player, long bPlayer black_player);
    void set_max_depth(long max_depth);
    long get_max_depth();
};
