enum wisdom_WebPlayer {
  "wisdom::Human",
  "wisdom::ChessEngine"
};

enum wisdom_WebColor {
  "wisdom::NoColor",
  "wisdom::White",
  "wisdom::Black",
};

enum wisdom_WebPiece {
  "wisdom::NoPiece",
  "wisdom::Pawn",
  "wisdom::Knight",
  "wisdom::Bishop",
  "wisdom::Rook",
  "wisdom::Queen",
  "wisdom::King"
};

enum wisdom_WebGameStatus {
    "wisdom::Playing",
    "wisdom::Checkmate",
    "wisdom::Stalemate",
    "wisdom::ThreefoldRepetitionReached",
    "wisdom::ThreefoldRepetitionAccepted",
    "wisdom::FivefoldRepetitionDraw",
    "wisdom::FiftyMovesWithoutProgressReached",
    "wisdom::FiftyMovesWithoutProgressAccepted",
    "wisdom::SeventyFiveMovesWithoutProgressDraw",
    "wisdom::InsufficientMaterialDraw",
};

[Prefix="wisdom::"]
interface WebColoredPiece {
    void WebColoredPiece (long id, wisdom_WebColor color, wisdom_WebPiece piece, long row, long col);
    attribute long id;
    attribute wisdom_WebColor color;
    attribute wisdom_WebPiece piece;
    attribute long row;
    attribute long col;
};

[Prefix="wisdom::"]
interface WebColoredPieceList {
    void WebColoredPieceList();
    [Value] attribute WebColoredPiece[] pieces;
    [Value] WebColoredPiece pieceAt (long index);
    attribute long length;
};

[Prefix="wisdom::"]
interface GameSettings {
    void GameSettings ();
    void GameSettings (wisdom_WebPlayer whitePlayer, wisdom_WebPlayer blackPlayer, long thinkingTime, long searchDepth);
    attribute wisdom_WebPlayer whitePlayer;
    attribute wisdom_WebPlayer blackPlayer;
    attribute long thinkingTime;
    attribute long searchDepth;
    attribute boolean debugLogging;
};

enum wisdom_WebDrawStatus {
    "wisdom::NotReached",
    "wisdom::Proposed",
    "wisdom::Accepted",
    "wisdom::Declined"
};

enum wisdom_WebDrawByRepetitionType {
    "wisdom::ThreefoldRepetition",
    "wisdom::FiftyMovesWithoutProgress"
};

[Prefix="wisdom::"]
interface WebGame {
    [Ref] WebColoredPieceList getPieceList();

    // Squares are in algebraic notation, such as "e2".
    boolean needsPawnPromotion (DOMString src, DOMString dst);

    // Returns the packed move for GameModel.notifyHumanMove(), or -1 if the
    // move is not legal.
    long makeHumanMove (DOMString src, DOMString dst, wisdom_WebPiece pieceType);

    void makeComputerMove (DOMString moveText);

    void setSettings([Const, Ref] GameSettings newSettings);

    boolean getInCheck();
    [Const] DOMString getMoveStatus();
    [Const] DOMString getGameOverStatus();
    attribute long moveNumber;
    long getGameId();

    wisdom_WebColor getCurrentTurn();
    wisdom_WebGameStatus getGameStatus();
    wisdom_WebPlayer getPlayerOfColor(wisdom_WebColor color);

    void setComputerDrawStatus(wisdom_WebDrawByRepetitionType type, wisdom_WebColor who, boolean accepted);
    void setHumanDrawStatus(wisdom_WebDrawByRepetitionType type, wisdom_WebColor who, boolean accepted);
};

[Prefix="wisdom::"]
interface GameModel {
    void GameModel();

    void sendPause();
    void sendUnpause();

    // Notify the chess engine about a human move.
    void notifyHumanMove (long packedMove);
    void notifyComputerMove();

    WebGame startNewGame();

    GameSettings getCurrentGameSettings();
    void setCurrentGameSettings (GameSettings newSettings);

    wisdom_WebColor getFirstHumanPlayerColor();
    wisdom_WebColor getSecondHumanPlayerColor();
};

