#include <emscripten.h>
#include <emscripten/wasm_worker.h>
#include <iostream>

// Include the type definitions for the glue code:
#include "wisdom-chess/wasm/game_model.hpp"
#include "wisdom-chess/wasm/game_settings.hpp"
#include "wisdom-chess/wasm/web_game.hpp"
#include "wisdom-chess/wasm/web_move.hpp"
#include "wisdom-chess/wasm/web_types.hpp"

// This is autogenerated glue code:
#include "wisdom-chess-wasm-glue.hpp"
