#include <emscripten.h>
#include <emscripten/wasm_worker.h>
#include <iostream>

// Include the type definitions for the glue code:
#include "game_model.hpp"
#include "game_settings.hpp"
#include "web_game.hpp"
#include "web_move.hpp"
#include "web_types.hpp"

// Map enums to the global namespace:
using wisdom_WebPlayer = wisdom::WebPlayer;
using wisdom_WebPiece = wisdom::WebPiece;
using wisdom_WebColor = wisdom::WebColor;
using wisdom_WebGameStatus = wisdom::WebGameStatus;

// This is autogenerated glue code:
#include "glue.hpp"
