enum wisdom_WebPlayer {
  "wisdom::Human",
  "wisdom::ChessEngine"
};

enum wisdom_WebColor {
  "wisdom::NoColor",
  "wisdom::White",
  "wisdom::Black",
};

enum wisdom_WebPiece {
  "wisdom::NoPiece",
  "wisdom::Pawn",
  "wisdom::Knight",
  "wisdom::Bishop",
  "wisdom::Rook",
  "wisdom::Queen",
  "wisdom::King"
};

[Prefix="wisdom::"]
interface WebColoredPiece {
    void WebColoredPiece(long color, long piece);
    attribute long color;
    attribute long piece;
};

[Prefix="wisdom::"]
interface WebColoredPieceList {
    void WebColoredPieceList();
    [Value] attribute WebColoredPiece[] pieces;
    attribute long length;
};

[Prefix="wisdom::"]
interface WebGame {
    void WebGame(long white_player, long black_player);

    void set_max_depth(long max_depth);
    long get_max_depth();
    void start_worker();

    WebColoredPieceList get_piece_list();
};
